name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  publish:
    name: Publish new feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Make folder dist
        run: mkdir ./dist

      - name: Build
        run: node ./index.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
